Implementation completed
prokey-io/prokey-link pull request #1
Opened 2022-03-29 13:43 UTC by houman-sanati

2022-03-31 08:38 UTC, hadideveloper requested changes

2022-03-31 08:38 UTC, hadideveloper commented on src/app/utils/Strings.ts
> +enum Strings {
These messages need improvement.

2022-03-31 08:38 UTC, hadideveloper commented on src/app/components/passphrase-dialog/passphrase-dialog.component.ts
> +      confirmPassphrase: ['', Validators.required],
Where do you check if confirmPassphrase equals to passphrase?

2022-03-31 17:22 UTC, houman-sanati commented on package-lock.json
> +{
fixed in [d9cd079](https://github.com/prokey-io/prokey-link/pull/1/commits/d9cd0799e6a474353017b8e2d40220c6ee0fbc9c)

2022-03-31 17:23 UTC, houman-sanati commented on src/app/app.component.ts
> +export class AppComponent implements OnInit {
fixed in [535863e](https://github.com/prokey-io/prokey-link/pull/1/commits/535863e63302b6c77eee0e7b71d57f00252c5844)

2022-03-31 17:23 UTC, houman-sanati commented on src/app/app.component.ts
> +  device: Device = null
fixed in [66ca249](https://github.com/prokey-io/prokey-link/pull/1/commits/66ca249d7fc4af165757c7503c926725d4311c72)

2022-03-31 17:24 UTC, houman-sanati commented on src/app/app.component.ts
> +        case 4:
fixed in [8a34c35](https://github.com/prokey-io/prokey-link/pull/1/commits/8a34c35b2a4f27df0f81380e600708b1ece6ce6c)

2022-04-02 09:40 UTC, houman-sanati commented on src/app/components/passphrase-dialog/passphrase-dialog.component.ts
> +      confirmPassphrase: ['', Validators.required],
fixed in [a2f53c8](https://github.com/prokey-io/prokey-link/pull/1/commits/a2f53c8a87dc0acaa82c0609f5d3a35c031997f1)

2022-04-04 05:17 UTC, houman-sanati commented on src/app/utils/Strings.ts
> +enum Strings {
fixed in [ce84bd9](https://github.com/prokey-io/prokey-link/pull/1/commits/ce84bd98c805870fccd5ae7247d352ef41c161dc)

2022-04-05 08:55 UTC, hadideveloper approved these changes

2022-04-05 09:00 UTC, merged